---
title: "Guest Lecture"
output: html_document
date: "2022-12-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")%>%
  janitor::clean_names()


pulse_tidy_data = pivot_longer(pulse_data,
                              bdi_score_bl:bdi_score_12m,
                              names_to = "visit",
                              names_prefix = "bdi_score_",
                              values_to = "bdi") %>%
  mutate(visit = replace(visit, visit == 'bl', '00m'),
         visit = factor(visit)) %>%
  arrange(id, visit)



```


```{r}
litters_data = read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(litter_number, ends_with("weight")) %>%
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd",
    values_to = "weight") %>%
  mutate(gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))
  

```



```{r}
analysis_result = tibble(
   group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

pivot_wider(analysis_result,
            names_from = "time",
            values_from = "mean")

```


```{r}
fellowship_of_the_ring = readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6")%>%
  mutate(movie = "fellowship_of_the_ring")

two_towers = readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_of_the_king = readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_of_the_king")


lotr_tidy = bind_rows(fellowship_of_the_ring, two_towers, return_of_the_king) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "gender",
    values_to = "words") %>%
  mutate(race = str_to_lower(race)) %>%
  select(movie, everything())

```

```{r}
pup_data = read_csv("./data/FAS_pups.csv") %>%
  janitor::clean_names() %>%
  mutate(
    sex = recode(sex,  "1" = "male", "2" = "female"),
    factor(sex))

litter_data = 
  read_csv("./data/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "date_of_tx"), sep = 3) %>%
  mutate(
    wt_gain = gd0_weight - gd18_weight,
    dose = str_to_lower(dose)
  )

fas_data = left_join(pup_data, litter_data, by = "litter_number")


```



```{r}
surv_os = read_csv("./survey_results/surv_os.csv") %>%
  janitor::clean_names() %>%
  rename(id = what_is_your_uni ,
         os = what_operating_system_do_you_use)

surv_program = read_csv("./survey_results/surv_program_git.csv") %>%
  janitor::clean_names() %>%
  rename(id = what_is_your_uni ,
         program = what_is_your_degree_program,
         git_exp = which_most_accurately_describes_your_experience_with_git)

surv_data = left_join(surv_os, surv_program, by = "id")

```

